import { addDays } from "date-fns";
import { fromZonedTime, toZonedTime } from "date-fns-tz";

/**
 * Per-step scheduling configuration. Times are expressed in the **contact's**
 * timezone (the human-facing perspective : "send at 9 AM at the client's
 * place"). The engine converts to the sale's timezone at task creation.
 *
 * Two output dates are computed independently :
 *  - `scheduledFor` : when the sale is expected to handle the task
 *  - `dueAt`        : when the task is considered late (optional)
 *
 * `dueAtAllDay` marks an "end-of-day" deadline (no specific hour ; the UI
 * shows just the date).
 */
export type TaskScheduling = {
  /** Hour (0..23) in the CONTACT's TZ. */
  preferredHour?: number;
  /** Business hours in the contact's TZ. */
  businessHours?: { start: number; end: number };
  /** Days allowed (0=Sunday..6=Saturday). Default Mon–Fri. */
  allowedWeekdays?: number[];
  /** Estimated duration of the task (slot reservation + anti-conflict). */
  estimatedDurationMinutes?: number;

  /** Fill the task's `scheduled_for` column. */
  setScheduledFor?: boolean;
  /** Business days from "today" before `scheduledFor`. 0 = today (or next ok day). */
  scheduledOffsetBusinessDays?: number;

  /** Fill the task's `due_at` column. */
  setDueAt?: boolean;
  /** Business days after `scheduledFor` for the deadline. */
  dueOffsetBusinessDays?: number;
  /** Hide the hour part of `due_at` in the UI (whole-day deadline). */
  dueAtAllDay?: boolean;
};

export const DEFAULT_SCHEDULING: Required<TaskScheduling> = {
  preferredHour: 9,
  businessHours: { start: 9, end: 18 },
  allowedWeekdays: [1, 2, 3, 4, 5],
  estimatedDurationMinutes: 5,
  setScheduledFor: true,
  scheduledOffsetBusinessDays: 0,
  setDueAt: false,
  dueOffsetBusinessDays: 1,
  dueAtAllDay: true,
};

export type ScheduleResult = {
  scheduledFor: Date | null;
  dueAt: Date | null;
  dueAtAllDay: boolean;
};

export class NoSchedulableSlotError extends Error {
  constructor(msg = "Could not schedule task within 14 days") {
    super(msg);
    this.name = "NoSchedulableSlotError";
  }
}

const SEARCH_HORIZON_DAYS = 14;

function pad2(n: number): string {
  return String(n).padStart(2, "0");
}

function weekdayInTz(utc: Date, tz: string): number {
  return toZonedTime(utc, tz).getDay();
}

/** Build a UTC instant at a given wall-clock (Y-M-D h:m) interpreted in `tz`. */
function utcAtWallClock(year: number, month1: number, day: number, hour: number, min: number, tz: string): Date {
  const s = `${year}-${pad2(month1)}-${pad2(day)}T${pad2(hour)}:${pad2(min)}:00`;
  return fromZonedTime(s, tz);
}

function setWallClockInTz(utc: Date, hour: number, min: number, tz: string): Date {
  const z = toZonedTime(utc, tz);
  return utcAtWallClock(z.getFullYear(), z.getMonth() + 1, z.getDate(), hour, min, tz);
}

/** Find the next calendar day (in `tz`) whose weekday is in `allowed`. */
function nextAllowedDay(fromUtc: Date, allowed: number[], tz: string): Date {
  let cursor = fromUtc;
  for (let i = 0; i < SEARCH_HORIZON_DAYS * 2; i++) {
    cursor = addDays(cursor, 1);
    if (allowed.includes(weekdayInTz(cursor, tz))) return cursor;
  }
  throw new NoSchedulableSlotError("No allowed weekday in the next 28 days");
}

/** Add N business days (skipping weekdays NOT in `allowed`) in `tz`. */
function addBusinessDaysInTz(start: Date, n: number, allowed: number[], tz: string): Date {
  let cursor = start;
  for (let i = 0; i < n; i++) {
    cursor = nextAllowedDay(cursor, allowed, tz);
  }
  return cursor;
}

/**
 * Compute `scheduledFor` + `dueAt` for a task generated by a sequence step.
 * Pure : no DB, no clock side-effect.
 *
 * Algorithm (all in CONTACT tz) :
 *  1. Start from today (or next allowed weekday).
 *  2. Skip `scheduledOffsetBusinessDays` more allowed days.
 *  3. Force the wall-clock to `preferredHour`.
 *  4. If the resulting moment is already in the past (e.g. preferredHour=9
 *     but `now`=11 AM), skip to the next allowed day at `preferredHour`.
 *  5. If `setDueAt`, compute `dueAt` by adding `dueOffsetBusinessDays` from
 *     `scheduledFor`. If `dueAtAllDay`, snap to 23:59 of that day in
 *     contactTz ; else use `preferredHour`.
 */
export function computeTaskSchedule(
  now: Date,
  scheduling: TaskScheduling,
  contactTz: string,
): ScheduleResult {
  const s: Required<TaskScheduling> = { ...DEFAULT_SCHEDULING, ...scheduling };

  if (!s.setScheduledFor && !s.setDueAt) {
    return { scheduledFor: null, dueAt: null, dueAtAllDay: false };
  }

  // 1 — start day : today if allowed, else next allowed.
  let dayUtc = now;
  if (!s.allowedWeekdays.includes(weekdayInTz(dayUtc, contactTz))) {
    dayUtc = nextAllowedDay(dayUtc, s.allowedWeekdays, contactTz);
  }
  // 2 — offset.
  dayUtc = addBusinessDaysInTz(dayUtc, s.scheduledOffsetBusinessDays, s.allowedWeekdays, contactTz);
  // 3 — force preferred hour.
  let target = setWallClockInTz(dayUtc, s.preferredHour, 0, contactTz);
  // 4 — if past, skip to next allowed day.
  if (target.getTime() < now.getTime()) {
    dayUtc = nextAllowedDay(dayUtc, s.allowedWeekdays, contactTz);
    target = setWallClockInTz(dayUtc, s.preferredHour, 0, contactTz);
  }

  const scheduledFor = s.setScheduledFor ? target : null;

  let dueAt: Date | null = null;
  let dueAllDay = false;
  if (s.setDueAt) {
    const base = scheduledFor ?? target;
    const dueDay = addBusinessDaysInTz(base, s.dueOffsetBusinessDays, s.allowedWeekdays, contactTz);
    dueAt = s.dueAtAllDay
      ? setWallClockInTz(dueDay, 23, 59, contactTz)
      : setWallClockInTz(dueDay, s.preferredHour, 0, contactTz);
    dueAllDay = s.dueAtAllDay;
  }

  return { scheduledFor, dueAt, dueAtAllDay: dueAllDay };
}
